### ISSUE TITLE
Runtime bug in Unity 2017.2

### ISSUE THREAD

**Issue by volfin** [Scramasax/Artimech#32]
UnityException: FindObjectsOfTypeAll is not allowed to be called from a ScriptableObject constructor (or instance field initializer), call it in OnEnable instead. Called from ScriptableObject 'stateEditor'.
See "Script Serialization" page in the Unity Manual for further details.
UnityEditor.EditorWindow.GetWindowPrivate (System.Type t, Boolean utility, System.String title, Boolean focus) (at C:/buildslave/unity/build/Editor/Mono/EditorWindow.cs:525)
UnityEditor.EditorWindow.GetWindow (System.Type t, Boolean utility, System.String title, Boolean focus) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorWindowBindings.gen.cs:51)
UnityEditor.EditorWindow.GetWindow (System.Type t, Boolean utility, System.String title) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorWindowBindings.gen.cs:31)
artiMech.stateEditor..ctor () (at Assets/Scripts/Common/statemachine/stateEditor/stateEditor.cs:32)

Seems the line it's faling on is line 32 in stateEditor.cs:

stateEditor window = (stateEditor)EditorWindow.GetWindow(typeof(stateEditor), true, "My Empty Window");

This only seems to happen when running with the State Editor window open.

(I tried moving the code to OnEnable() as they suggest, and that does seem to solve it.

**Comment by Scramasax** [comment]
Thank you for the input and a fix is in for this.
